# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress
#   namespace: jenkins-ns
# spec:
#   rules:
#   - http:
#       paths:
#       - path: "/"
#         backend:
#           service:
#             name: jenkins-service
#             port:
#               number: 8080
#         pathType: "ImplementationSpecific"
# status:
#   loadBalancer: {}
