apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: dev-shared-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: gcr.io/anwer-gcp/myapp:latest
          resources:
          ports:
            - name: httpport
              containerPort: 80