---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-server-service"
  namespace: "dev-shared-services"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
  selector:
    app: "web-server"
  type: "NodePort"
