apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: "dev-shared-services"
spec:
  rules:
  - http:
      paths:
      - path: "/"
        backend:
          service:
            name: "web-server-service"
            port:
              number: 5000
        pathType: "ImplementationSpecific"
status:
  loadBalancer: {}
