apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: shared-services
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-server
